### ISSUE TITLE
Simplification of a new dataset

### ISSUE THREAD

**Issue by akileshbadrinaaraayanan** [hardmaru/sketch-rnn-datasets#1]
Hi,

Thank you for providing this wonderful reference. 
I have a new set of svgs on which I want to train or evaluate sketch-rnn model. Could you please direct me to appropriate references (.py files) for the simplification procedure followed mentioned here (https://github.com/googlecreativelab/quickdraw-dataset). 

'''
We've simplified the vectors, removed the timing information, and positioned and scaled the data into a 256x256 region. The data is exported in ndjson format with the same metadata as the raw format. The simplification process was:

    Align the drawing to the top-left corner, to have minimum values of 0.
    Uniformly scale the drawing, to have a maximum value of 255.
    Resample all strokes with a 1 pixel spacing.
    Simplify all strokes using the Ramer–Douglas–Peucker algorithm with an epsilon value of 2.0.
'''

Thanks,
Akilesh

**Comment by nile649** [comment]
where you able to create your own custom dataset?
