### ISSUE TITLE
associating stroke data with omniglot image data

### ISSUE THREAD

**Issue by ostwind** [hardmaru/sketch-rnn-datasets#2]
Thank you for the python version of the omniglot stroke data!

Given a numpy array of stroke movements found in omniglot.npz, is there an auxiliary file to identify which image in the original omniglot is linked to this? ( something along the lines of alphabet - letter - drawing number ) My hope is that a model trained on omniglot can utilize this additional info. 

Thank you again.

**Comment by hardmaru** [comment]
Hi @ostwind 

Unfortunately that information is lost when I clumsily crate extracted the version from the matlab omniglot files years ago. If you happen to do it correctly, and you are able to link to the original data, please feel to submit a PR!

Cheers.
